version: '3.8'

services:
  maskgct:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ../models:/app/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
